### ISSUE TITLE
Dush fails after 10.3 update

### ISSUE THREAD

**Issue by lieb77** [drush-ops/drush#4444]
**Describe the bug**
Composer update gave me drush 10.3 but now every drush command fails with
ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\core\MessengerCommands::__construct(), 0 passed in /drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 and exactly 1 expected in /drupal/vendor/drush/drush/src/Drupal/Commands/core/MessengerCommands.php on line 16 #0 /drupal/web/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drush\Drupal\Commands\core\MessengerCommands->__construct()

**To Reproduce**
Update to 10.3 , run drush anything

Was working fine with drush 10.2.2

### System Configuration
I got the same error on 2 different servers, both with the same config.

Drupal 8.9.1
PHP 7.3
Drush: 10.3
Drush launcher: 0.6.0

**Comment by weitzman** [comment]
Did you try `drush cr`?

**Comment by lieb77** [comment]
Moshe,
 First let me thank you for Drush. I couldn't do Drupal without it.

I did try drush cr and got the same error. Then I tried drush cc drush
thinking maybe that was still in there, same error.
Then after receiving this email I tried it again and it worked. Drush 10.3
is now functioning. I suppose after drush cr did not work the first time I
could have tried clearing the cache from within Drupal.

With composer, when updating core or modules I always run drush updb after.
I suppose updating drush presents a special case.

Thanks for your help.

Paul Lieberman
Corvallis, OR

**Comment by therobyouknow** [comment]
> Did you try `drush cr`?

Thank you so much. What relief!

Exact same issue as @lieb77 and that's why I came here after searching for info about this error.

Solved for my situation, thank you.

I will include output of my error to help this solution be picked up by others when they search for it - thanks again!

```
# ./drush
ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\core\MessengerCommands::__construct(), 0 passed in docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 and exactly 1 expected in vendor/drush/drush/src/Drupal/Commands/core/MessengerCommands.php on line 16 #0 docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(259): Drush\Drupal\Commands\core\MessengerCommands->__construct()
#1 docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'messenger.comma...')
#2 docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(434): Drupal\Component\DependencyInjection\Container->get('messenger.comma...', 1)
#3 docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(273): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#4 docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#5 vendor/drush/drush/src/Boot/DrupalBoot8.php(279): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#6 vendor/drush/drush/src/Boot/DrupalBoot8.php(245): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#7 vendor/drush/drush/src/Boot/BootstrapManager.php(293): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), NULL)
#8 vendor/drush/drush/src/Boot/BootstrapManager.php(493): Drush\Boot\BootstrapManager->doBootstrap(5, 6, NULL)
#9 vendor/drush/drush/src/Boot/BootstrapManager.php(427): Drush\Boot\BootstrapManager->bootstrapMax(6)
#10 vendor/drush/drush/src/Boot/BootstrapManager.php(396): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(-2, Object(Consolidation\AnnotatedCommand\AnnotationData))
#11 vendor/drush/drush/src/Boot/BootstrapHook.php(28): Drush\Boot\BootstrapManager->bootstrapToPhase('max', Object(Consolidation\AnnotatedCommand\AnnotationData))
#12 vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(34): Drush\Boot\BootstrapHook->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#13 vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#14 vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#15 vendor/consolidation/annotated-command/src/AnnotatedCommand.php(289): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Drush\Symfony\DrushArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#16 vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 vendor/drush/drush/drush(4): require('/var/www/probon...')
#24 {main}
ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\core\MessengerCommands::__construct(), 0 passed in docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 259 and exactly 1 expected in Drush\Drupal\Commands\core\MessengerCommands->__construct() (line 16 of vendor/drush/drush/src/Drupal/Commands/core/MessengerCommands.php).
 [warning] Drush command terminated abnormally.
# 
```
