### ISSUE TITLE
Drush crashes after upgrading to 10.0.2 on Drupal 8.7.9

### ISSUE THREAD

**Issue by hansfn** [drush-ops/drush#4264]
**Describe the bug**
Drush 10.0.2 (on Drupal 8.7.9) crashes with error:

```
[error]  ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\config\ConfigCommands::__construct(), 1 passed in /var/www/[...]/web/core/lib/Drupal/Component/DependencyInjection/Container.php on line 269 and exactly 2 expected in Drush\Drupal\Commands\config\ConfigCommands->__construct() (line 54 of /var/www/[...]/vendor/drush/drush/src/Drupal/Commands/config/ConfigCommands.php
[...]
```

**To Reproduce**
Happily running Drush 9.7.1 on Drupal 8.7.9. Upgrading to Drush 10.0.2 with
```
composer update drush/drush --with-dependencies
```
and Drush crashes. If I then update Drupal to 8.7.10 using
```
composer update drupal/core webflo/drupal-core-require-dev --with-dependencies
```
Drush works again.

**Expected behavior**
Drush working after upgrade.

**Actual behavior**
Drush crashing.

**Workaround**
Upgrade Drupal to 8.7.10.

I'm not saying that Drush 10.0.2 is incompatible with Drupal 8.7.9. I'm just reporting that it failed to work for me. I don't have time to make a fresh install of Drupal 8.7.9 and Drush 10.0.2 and see if it works or not.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.0.2
| Drupal version? | 8.7.9 / 8.7.10
| PHP version     | 7.3.11
| OS?             | Linux

**Additional information**

**Comment by weitzman** [comment]
Have you tried a `drush cr`? This is needed anytime you change your code (i.e. a composer update). This can sometimes fix the issue.

**Comment by hansfn** [comment]
To be honest, I didn't try because Drush failed when running it without any arguments (`vendor/bin/drush`).  Feel free to close this issue if you think `drush cr` would have worked even if it didn't work without any arguments.

**Comment by BR0kEN-** [comment]
### Environment

- Drupal 8.8.5
- Drush 9.7.2 updated to Drush 10.2.2 via `composer update`

### Check the update

```bash
$ drush status bootstrap
ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\config\ConfigCommands::__construct(), 1 passed in /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 269 and exactly 2 expected in /home/catuser/app/public/vendor/drush/drush/src/Drupal/Commands/config/ConfigCommands.php on line 54 #0 /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(269): Drush\Drupal\Commands\config\ConfigCommands->__construct(Object(Drupal\Core\Config\ConfigFactory))
#1 /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'config.commands')
#2 /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(487): Drupal\Component\DependencyInjection\Container->get('config.commands', 1)
#3 /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(326): Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters(Array)
#4 /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php(173): Drupal\Component\DependencyInjection\Container->createService(Array, 'drush.command.s...')
#5 /home/catuser/app/public/vendor/drush/drush/src/Boot/DrupalBoot8.php(290): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#6 /home/catuser/app/public/vendor/drush/drush/src/Boot/DrupalBoot8.php(256): Drush\Boot\DrupalBoot8->addDrupalModuleDrushCommands(Object(Drush\Boot\BootstrapManager))
#7 /home/catuser/app/public/vendor/drush/drush/src/Boot/BootstrapManager.php(293): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(Object(Drush\Boot\BootstrapManager), NULL)
#8 /home/catuser/app/public/vendor/drush/drush/src/Boot/BootstrapManager.php(493): Drush\Boot\BootstrapManager->doBootstrap(5, 6, NULL)
#9 /home/catuser/app/public/vendor/drush/drush/src/Boot/BootstrapManager.php(427): Drush\Boot\BootstrapManager->bootstrapMax(6)
#10 /home/catuser/app/public/vendor/drush/drush/src/Boot/BootstrapManager.php(396): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(-2, Object(Consolidation\AnnotatedCommand\AnnotationData))
#11 /home/catuser/app/public/vendor/drush/drush/src/Boot/BootstrapHook.php(28): Drush\Boot\BootstrapManager->bootstrapToPhase('max', Object(Consolidation\AnnotatedCommand\AnnotationData))
#12 /home/catuser/app/public/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(34): Drush\Boot\BootstrapHook->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#13 /home/catuser/app/public/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php(27): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook(Object(Drush\Boot\BootstrapHook), Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#14 /home/catuser/app/public/vendor/consolidation/annotated-command/src/CommandProcessor.php(145): Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Consolidation\AnnotatedCommand\AnnotationData))
#15 /home/catuser/app/public/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(289): Consolidation\AnnotatedCommand\CommandProcessor->initializeHook(Object(Drush\Symfony\DrushArgvInput), Array, Object(Consolidation\AnnotatedCommand\AnnotationData))
#16 /home/catuser/app/public/vendor/symfony/console/Command/Command.php(221): Consolidation\AnnotatedCommand\AnnotatedCommand->initialize(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /home/catuser/app/public/vendor/symfony/console/Application.php(1005): Symfony\Component\Console\Command\Command->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /home/catuser/app/public/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /home/catuser/app/public/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /home/catuser/app/public/vendor/drush/drush/src/Runtime/Runtime.php(118): Symfony\Component\Console\Application->run(Object(Drush\Symfony\DrushArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /home/catuser/app/public/vendor/drush/drush/src/Runtime/Runtime.php(49): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/catuser/app/public/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#23 /home/catuser/app/public/vendor/drush/drush/drush(4): require('/home/catuser/a...')
#24 {main}
ArgumentCountError: Too few arguments to function Drush\Drupal\Commands\config\ConfigCommands::__construct(), 1 passed in /home/catuser/app/public/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 269 and exactly 2 expected in Drush\Drupal\Commands\config\ConfigCommands->__construct() (line 54 of /home/catuser/app/public/vendor/drush/drush/src/Drupal/Commands/config/ConfigCommands.php).
 [warning] Drush command terminated abnormally.
```

The same result for `updb`, `cr` etc.

### Solution

Turned out the problem is pretty easy resolvable however I don't understand how to roll this out to a remote environment with no headache.

Drush 10 changed some of its services' definitions and before the `composer update` Drupal DI container was precached. The next call to `drush` resulted in a service creation error because a cached container had stale service definition.

The solution is to clean the `cache_container` table (or another place where the container cache is stored) however as was said this brings some discomfort because before using `drush` deployed somewhere you have to take care of clearing that cache in an automated way. And it can't be `drush` itself. It can't be something like `drush sqlq "truncate table cache_container"` or `drush sql-connect` and SQL query.

**Comment by weitzman** [comment]
I would think that a `drush cr` right after deploying the code would work. Thats what the new [deploy](https://github.com/drush-ops/drush/blob/master/src/Commands/core/DeployCommands.php) command does.

The drush sql commands dont rely on the Drupal container so should be fine to use as well.

**Comment by jcicero518** [comment]
It does seem to fix it (drush cr). I had the same problem, just typing drush would throw the error mentioned above so I looked this up. Kudos @weitzman for making the point about the container.

**Comment by thafner** [comment]
Just had the same issue with Drush 10.6.x and clearing the cache `drush cr` solved for me as well.
